# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='updatedUserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, null=True)),
                ('mobilenumber', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
